create or replace database health_db;
use database health_db;
create or replace schema health_schema;
use schema health_schema;
CREATE TABLE PATIENTS (
    PATIENT_ID INT,
    NAME STRING,
    AGE INT,
    DISEASE STRING,
    SSN STRING
);

CREATE TABLE DOCTORS (
    DOCTOR_ID INT,
    NAME STRING,
    SPECIALIZATION STRING
);

CREATE TABLE APPOINTMENTS (
    APPOINTMENT_ID INT,
    PATIENT_ID INT,
    DOCTOR_ID INT,
    VISIT_DATE DATE
);

INSERT INTO PATIENTS VALUES
(1,'Rahul',45,'Diabetes','123-45-6789'),
(2,'Sita',30,'Heart','987-65-4321');

INSERT INTO DOCTORS VALUES
(101,'Dr.Sharma','Cardiology'),
(102,'Dr.Reddy','Endocrinology');

INSERT INTO APPOINTMENTS VALUES
(1001,1,101,'2025-01-10'),
(1002,2,102,'2025-01-11');
use role securityadmin;
create role DOCTOR_ROLE;
create role nurse_role;
create role analyst_role;
grant usage on database health_db to role DOCTOR_ROLE;
GRANT USAGE ON DATABASE HEALTH_DB TO ROLE NURSE_ROLE;
GRANT USAGE ON DATABASE HEALTH_DB TO ROLE ANALYST_ROLE;

GRANT USAGE ON SCHEMA health_schema TO ROLE DOCTOR_ROLE;
GRANT USAGE ON SCHEMA health_schema TO ROLE NURSE_ROLE;
GRANT USAGE ON SCHEMA health_schema TO ROLE ANALYST_ROLE;

-- Table access
GRANT SELECT, INSERT, UPDATE ON TABLE PATIENTS TO ROLE DOCTOR_ROLE;
GRANT SELECT ON TABLE PATIENTS TO ROLE NURSE_ROLE;
GRANT SELECT ON TABLE PATIENTS TO ROLE ANALYST_ROLE;


GRANT SELECT ON TABLE DOCTORS TO ROLE DOCTOR_ROLE;
GRANT SELECT ON TABLE APPOINTMENTS TO ROLE DOCTOR_ROLE;
GRANT SELECT ON TABLE APPOINTMENTS TO ROLE ANALYST_ROLE;

CREATE USER DR_USER PASSWORD='Doctor123';
CREATE USER NURSE_USER PASSWORD='Nurse123';
CREATE USER ANALYST_USER PASSWORD='Analyst123';

GRANT ROLE DOCTOR_ROLE TO USER DR_USER;
GRANT ROLE NURSE_ROLE TO USER NURSE_USER;
GRANT ROLE ANALYST_ROLE TO USER ANALYST_USER;

use role securityadmin;
create or replace network policy office_only allowed_ip_list=('192.168.1.0/24',--/24 means all addresses from .0 to .255
'10.0.0.0/24','122.175.127.154')
blocked_ip_list=()
comment='allow office network only';
SELECT SYSTEM$CLIENT_IP();
SELECT EVENT_TIMESTAMP, CLIENT_IP
FROM TABLE(INFORMATION_SCHEMA.LOGIN_HISTORY())
ORDER BY EVENT_TIMESTAMP DESC;
show network policies;
desc network policy office_only;
alter user analyst_user set network_policy=office_only;
use role accountadmin;
show users like 'analyst_user';
show parameters like 'network_policy' in user analyst_user;
alter user analyst_user unset network_policy;
ALTER ACCOUNT UNSET NETWORK_POLICY;
alter account set network_policy=office_only;

create masking policy mask as (val STRING) returns string->
case 
    when current_role()='HR_MANAGER_ROLE'
then val
    else 'XXX-XX-XXXX'
end 
comment='Mask for non-HR users';
show masking policies;
drop table emp;
CREATE OR REPLACE TABLE EMP (
    ID INT,
    NAME VARCHAR(50),
    SALARY NUMBER(10,2),
    DEPT NUMBER,
    SSN varchar
);

INSERT INTO EMP VALUES (1, 'John Smith', 55000, 10, 123456789),(2, 'Alice Johnson', 62000, 20, 234567890),(3, 'Robert Brown', 48000, 10, 345678901),(4, 'Emily Davis', 75000, 30, 456789012),(5, 'Michael Wilson', 67000, 20, 567890123),(6, 'Sarah Miller', 59000, 10, 678901234),(7, 'David Taylor', 82000, 30, 789012345),(8, 'Laura Anderson', 71000, 20, 890123456),(9, 'James Thomas', 53000, 10, 901234567),(10, 'Olivia Martin', 76000, 30, 112233445);
alter table emp modify column ssn set masking policy mask;
create role hr_manager_role;
grant role hr_manager_role to user analyst_user;

CREATE DATABASE IF NOT EXISTS ENTERPRISE_DB;
CREATE SCHEMA IF NOT EXISTS ENTERPRISE_DB.ANALYTICS;
CREATE OR REPLACE TABLE ENTERPRISE_DB.ANALYTICS.SALES_DATA (
    ORDER_ID INT,
    CUSTOMER_NAME STRING,
    PRODUCT STRING,
    SALES_AMOUNT NUMBER(10,2),
    COUNTRY STRING
);
ALTER TABLE ENTERPRISE_DB.ANALYTICS.SALES_DATA DROP COLUMN COUNTRY;

ALTER TABLE ENTERPRISE_DB.ANALYTICS.SALES_DATA ADD COLUMN REGION VARCHAR;

INSERT INTO ENTERPRISE_DB.ANALYTICS.SALES_DATA VALUES
(1, 'Raj Kumar', 'Laptop', 75000, 'India'),
(2, 'John Smith', 'Tablet', 45000, 'USA'),
(3, 'Priya Sharma', 'Mobile', 25000, 'India'),
(4, 'Emily Davis', 'Monitor', 30000, 'UK'),
(5, 'Amit Verma', 'Keyboard', 5000, 'India');
create role data_analyst;
grant role data_analyst to user analyst_user;
CREATE ROLE APAC_ANALYST_ROLE;
CREATE ROLE AMERICAS_ANALYST_ROLE;
USE ROLE SECURITYADMIN;

CREATE USER APAC_USER
PASSWORD = 'Apac@123'
DEFAULT_ROLE = APAC_ANALYST_ROLE
MUST_CHANGE_PASSWORD = TRUE;

CREATE USER AMERICAS_USER
PASSWORD = 'Americas@123'
DEFAULT_ROLE = AMERICAS_ANALYST_ROLE
MUST_CHANGE_PASSWORD = TRUE;

CREATE USER SYSADMIN_USER
PASSWORD = 'Sysadmin@123'
DEFAULT_ROLE = SYSADMIN
MUST_CHANGE_PASSWORD = TRUE;

use role sysadmin;
ALTER TABLE ENTERPRISE_DB.ANALYTICS.SALES_DATA
ADD ROW ACCESS POLICY REGION_FILTER ON (REGION);
CREATE ROW ACCESS POLICY REGION_FILTER AS 
(REGION STRING) RETURNS BOOLEAN ->
CASE
    WHEN CURRENT_ROLE() = 'APAC_ANALYST_ROLE' AND REGION = 'india' THEN TRUE
    WHEN CURRENT_ROLE() = 'AMERICAS_ANALYST_ROLE' AND REGION = 'usa' THEN TRUE
    WHEN CURRENT_ROLE() = 'SYSADMIN' THEN TRUE
    ELSE FALSE
END;
ALTER TABLE SALES_DATA ADD ROW ACCESS POLICY REGION_FILTER ON (REGION);
USE ROLE ACCOUNTADMIN;
CREATE TAG DATA_SENSITIVITY 
ALLOWED_VALUES('PUBLIC','INTERNAL','CONFIDENTIAL','RESTRICTED') 
COMMENT='DATA SENSITIVITY CLASSIFICATION';


USE ROLE ACCOUNTADMIN;
ALTER USER JAHNAVI04 UNSET NETWORK_POLICY;
SHOW PARAMETERS LIKE 'NETWORK_POLICY' FOR USER JAHNAVI04;
ALTER ACCOUNT UNSET NETWORK_POLICY;
SHOW PARAMETERS LIKE 'NETWORK_POLICY' IN ACCOUNT;
SELECT CURRENT_ROLE();
SHOW NETWORK POLICIES;
DROP NETWORK POLICY OFFICE_ONLY;
SHOW USERS;
GRANT ROLE ACCOUNTADMIN TO USER JANU;
